/* eslint-disable */
var levelData = {
  creatorName: "彡 𝐖𝕀єη𝔢ʳ∂𝓞ｇ彡 & maxxr69420",
  objectBlueprintGridText: `
  ramp	lava	lava	water	lava	lava	lava	lava
  tall	lava	lava	lava	lava	water	lava	lava
  tall	tall	lava	lava	lava	lava	water	water
  lava	tall	tall	lava	lava	lava	lava	lava
  lava	lava	tall@dt=2,da=3,dz=3,dr=2,ds=6	lava	water	lava	lava	lava
  lava	lava	tall@dt=2,dz=2	lava	lava	lava	lava	lava
  lava	lava	tall@dt=2,dz=1	lava	lava	lava	lava	lava
  lava	lava	tall@dt=2,dz=2	lava	lava	lava	lava	lava
  void@dt=2,dz=1	void@dt=2,dz=1	tall@dt=2,dz=2	void@dt=2,dz=1	void@dt=2,dz=1	void@dt=2,dz=1	void@dt=2,dz=1	void@dt=2,dz=1
  void@dt=2,dz=1	tall@dt=2,dz=2	tall@dt=2,dz=4	tall@dt=2,dz=2	void@dt=2,dz=1	void@dt=2,dz=1	void@dt=2,dz=1	void@dt=2,dz=1
  tall@dt=2,dz=2	tall@dt=2,dz=2	lava	tall@dt=2,dz=2	tall@dt=2,dz=2	lava	lava	lava
  tall@dt=2,dz=2	lava	lava	lava	lava	lava	lava	lava
  tall@dt=2,dz=2	lava	lava	lava	lava	lava	lava	lava
  tall@dt=2,dz=2	lava	water	lava	tall@dt=2,dz=2	lava	lava	lava
  void@dt=2,dz=1	void@dt=2,dz=1	lava	void@dt=2,dz=1	tall@dt=2,dz=2	void@dt=2,dz=1	void@dt=2,dz=1	void@dt=2,dz=1
  void@dt=2,dz=1	void@dt=2,dz=1	void@dt=2,dz=1	void@dt=2,dz=1	tall@dt=2,dz=2	void@dt=2,dz=1	void@dt=2,dz=1	void@dt=2,dz=1
  ramp@dt=2,dz=2	lava	lava	lava	tall@dt=2,dz=2	lava	water	lava
  tall@dt=2,dz=2	lava	lava	lava	lava	lava	lava	lava
  tall@dt=2,dz=2	lava	lava	lava	lava	lava	lava	lava
  tall@dt=2,dz=2	tall@dt=2,dz=2	lava	tall@dt=2,dz=2	tall@dt=2,dz=2	lava	lava	lava
  void@dt=2,dz=1	tall@dt=2,dz=2	tall@dt=2,dz=2	tall@dt=2,dz=2	void@dt=2,dz=1	void@dt=2,dz=1	void@dt=2,dz=1	void@dt=2,dz=1
  void@dt=2,dz=1	void@dt=2,dz=1	tall@dt=2,dz=2	void@dt=2,dz=1	void@dt=2,dz=1	void@dt=2,dz=1	void@dt=2,dz=1	void@dt=2,dz=1
  lava	lava	short@da=4,dt=1	lava	lava	water	lava	lava
  lava	lava	short@da=-4,dt=1	lava	lava	lava	lava	water
  lava	lava	short@da=4,dt=1	lava	lava	lava	lava	lava
  lava	lava	short@da=-4,dt=1	lava	lava	lava	lava	lava
  lava	lava	ramp@dt=2,dz=2	lava	lava	lava	lava	lava
  water	lava	tall@dt=2,dz=2	tall@dt=2,dz=2	lava	lava	lava	lava
  lava	lava	lava	tall@dt=2,dz=2	tall@dt=2,dz=2,da=4	lava	lava	lava
  lava	lava	lava	lava	tall@dt=2,dz=2,da=4	lava	water	lava
  lava	lava	lava	tall@dt=2,dz=2	tall@dt=2,dz=2,da=4	lava	lava	lava
  lava	lava	tall@dt=2,dz=2	tall@dt=2,dz=2	lava	lava	lava	lava
  short@dt=2,dz=1	short@dt=2,dz=1	tall@dt=2,dz=2	short@dt=2,dz=1	short@dt=2,dz=1	short@dt=2,dz=1	short@dt=2,dz=1	short@dt=2,dz=1
  short@dt=2,dz=1	short@dt=2,dz=1	tall@dt=2,dz=2	short@dt=2,dz=1	short@dt=2,dz=1	short@dt=2,dz=1	short@dt=2,dz=1	short@dt=2,dz=1
  lava	water	tall	water	lava	lava	lava	lava
  lava	water	tall	water	lava	lava	lava	lava
  lava	water	tall	tall@dt=2,dz=2	lava	lava	lava	lava
  lava	lava	water	tall@dt=2,dz=2	lava	lava	lava	lava
  lava	lava	tall	tall	water	water	water	lava
  lava	lava	tall	water	lava	lava	lava	lava
  lava	lava	tall@dt=2,dz=2	tall@dt=2,dz=2	tall	lava	lava	lava
  lava	lava	lava	lava	tall	tall	water	lava
  lava	tall	lava	lava	water	tall	water	lava
  water	tall	water	lava	lava	lava	lava	lava
  water	tall	water	lava	lava	lava	lava	lava
  lava	tall	tall	water	lava	lava	lava	lava
  lava	lava	water	short	water	lava	lava	lava
  water	water	water	short	water	water	water	water
  tall	tall	tall	tall	tall	tall	tall	tall
  tall	tall	tall	tall	tall	tall	tall	tall
  tall	tall	tall	tall	tall	tall	tall	tall
  tall	tall	tall	tall	tall	tall	tall	tall
  tall	tall	tall	tall	tall	tall	tall	tall
  tall	tall	tall	tall	tall	tall	tall	tall
  tall	tall	tall	tall	tall	tall	tall	tall
  tall	tall	tall	tall	tall	tall	tall	tall
  tall	tall	tall	tall	tall	tall	tall	tall
  water	short	water	water	water	short	water	water
  water	short	water	water	water	short	water	lava
  water	short	water	water	water	short	water	lava
  lava	water	short	water	short	water	lava	lava
  lava	lava	water	short	water	water	lava	lava
  lava	lava	water	short	water	water	lava	lava
  lava	lava	water	short	short	short	water	lava
  lava	lava	lava	water	water	short	water	lava
  lava	lava	lava	water	water	short	water	lava
  lava	lava	water	short	short	short	water	lava
  lava	lava	water	short	water	water	lava	lava
  lava	lava	water	short	water	lava	lava	lava
  lava	water	short	water	lava	lava	lava	lava
  water	short	water	lava	lava	lava	lava	lava
  water	short	lava	lava	lava	lava	lava	lava
  water	short	water	lava	lava	lava	lava	lava
  water	short	water	lava	lava	lava	lava	lava
  lava	water	short	water	lava	lava	lava	lava
  lava	water	short	water	lava	lava	lava	lava
  water	water	water	short	water	water	water	water
  short	short	short	short	short	short	short	short
  ramp	ramp	ramp	ramp	ramp	ramp	ramp	ramp
  ramp	ramp	ramp	ramp	ramp	ramp	ramp	ramp
  tall	tall	tall	tall	tall	tall	tall	tall
  tall	tall	tall	tall	tall	tall	tall	tall
  short@dt=2,dz=1	short@dt=2,dz=1	short@dt=2,dz=1	short@dt=2,dz=1	short@dt=2,dz=1	short@dt=2,dz=1	short@dt=2,dz=1	short@dt=2,dz=1
  short@dt=2,dz=1	short@dt=2,dz=1	short@dt=2,dz=1	short@dt=2,dz=1	short@dt=2,dz=1	short@dt=2,dz=1	short@dt=2,dz=1	short@dt=2,dz=1
  lava	short@dt=2,dz=1	lava	lava	lava	lava	lava	lava
  short@dt=2,dz=1	short@dt=2,dz=1	short@dt=2,dz=1	short@dt=2,dz=1	short@dt=2,dz=1	short@dt=2,dz=1	short@dt=2,dz=1	short@dt=2,dz=1
  short@dt=2,dz=1	short@dt=2,dz=1	short@dt=2,dz=1	short@dt=2,dz=1	short@dt=2,dz=1	short@dt=2,dz=1	short@dt=2,dz=1	short@dt=2,dz=1
  lava	lava	lava	lava	short@dt=2,dz=1	lava	lava	lava
  short@dt=2,dz=1	short@dt=2,dz=1	short@dt=2,dz=1	short@dt=2,dz=1	short@dt=2,dz=1	short@dt=2,dz=1	short@dt=2,dz=1	short@dt=2,dz=1
  short@dt=2,dz=1	short@dt=2,dz=1	short@dt=2,dz=1	short@dt=2,dz=1	short@dt=2,dz=1	short@dt=2,dz=1	short@dt=2,dz=1	short@dt=2,dz=1
  water	water	water	water	water	water	water	water
  short@dt=2,dz=1	short@dt=2,dz=1	short@dt=2,dz=1	short@dt=2,dz=1	short@dt=2,dz=1	short@dt=2,dz=1	short@dt=2,dz=1	short@dt=2,dz=1
  short@dt=2,dz=1	short@dt=2,dz=1	short@dt=2,dz=1	short@dt=2,dz=1	short@dt=2,dz=1	short@dt=2,dz=1	short@dt=2,dz=1	short@dt=2,dz=1
  short@dt=2,dz=1	short@dt=2,dz=1	short@dt=2,dz=1	short@dt=2,dz=1	short@dt=2,dz=1	short@dt=2,dz=1	short@dt=2,dz=1	short@dt=2,dz=1
  short@dt=2,dz=1	short@dt=2,dz=1	short@dt=2,dz=1	short@dt=2,dz=1	short@dt=2,dz=1	short@dt=2,dz=1	short@dt=2,dz=1	short@dt=2,dz=1
  void@dt=2,dz=1	void@dt=2,dz=1	void@dt=2,dz=1	void@dt=2,dz=1	void@dt=2,dz=1	void@dt=2,dz=1	void@dt=2,dz=1	void@dt=2,dz=1
`,
};
