/* eslint-disable */
var levelData = {
  creatorName: "彡 𝐖𝕀єη𝔢ʳ∂𝓞ｇ彡",
  objectBlueprintGridText: `
short	void	void	void	void	void	void	void
short	void	void	void	void	void	void	void
short	void	void	void	void	void	void	void
short	void	void	void	void	void	void	void
short	void	void	void	void	void	void	void
short	void	void	void	void	void	void	void
void	short	void	void	void	void	void	void
void	void	short	void	void	void	void	void
void	void	void	short	void	void	void	void
void	void	void	short	void	void	void	void
void	void	short	void	void	void	void	void
void	short	void	void	void	void	void	void
void	short	void	void	void	void	void	void
void	void	short	void	void	void	void	void
void	void	void	short	void	void	void	void
void	void	void	short	void	void	void	void
void	void	void	short	void	void	void	void
void	void	void	tall	void	void	void	void
void	void	void	tall	void	void	void	short
void	void	void	tall	void	void	void	short
void	void	void	tall	void	void	void	short
void	void	void	tall	void	void	void	void
void	void	void	tall	void	void	void	void
void	void	void	tall	void	void	void	void
void	void	void	void	tall	void	void	void
void	void	void	void	void	tall	void	void
void	void	void	void	void	void	tall	void
void	void	void	void	void	void	void	tall
tall	void	void	void	void	void	void	void
void	tall	void	void	void	void	void	void
void	void	tall	void	void	void	void	void
void	void	tall	void	void	void	void	void
void	void	tall	void	void	void	void	void
short	short	short	short	short	short	short	short
short	short	short	short	short	short	short	short
short	lava	lava	lava	lava	lava	lava	lava
short	short	short	short	short	short	short	short
short	short	short	short	short	short	short	short
short	short	short	short	short	short	short	short
lava	lava	lava	lava	short	lava	lava	lava
void	void	void	void	short	void	void	void
void	void	void	void	short	void	void	void
void	void	void	void	short	void	void	void
void	void	void	void	short	void	void	void
void	void	void	void	short	void	void	void
void	void	void	short	void	void	void	void
void	void	void	short	void	void	void	void
void	void	void	short	void	void	void	void
tall	tall	tall	tall	tall	tall	tall	tall
tall	tall	tall	tall	tall	tall	tall	tall
tall	tall	tall	tall	tall	tall	tall	tall
void	void	void	short	void	void	void	void
void	void	void	short	void	void	void	void
void	void	void	short	void	void	void	void
void	void	void	short	void	void	void	void
void	void	void	short	void	void	void	void
void	void	void	short	void	void	void	void
void	void	short	void	void	void	void	void
void	void	short	void	void	void	void	void
void	short	void	void	void	void	void	void
void	short	void	void	void	void	void	void
short	void	void	void	void	void	void	void
short	void	void	void	void	void	void	void
void	short	void	void	void	void	void	void
void	short	void	void	void	void	void	void
void	void	short	void	void	void	void	void
void	void	short	void	void	void	void	void
void	void	void	short	void	void	void	void
void	void	void	short	void	void	void	void
void	void	void	void	short	void	void	void
void	void	void	void	short	void	void	void
void	void	void	void	void	short	void	void
void	void	void	void	void	short	void	void
void	void	void	void	void	void	short	void
void	void	void	void	void	void	short	void
void	void	void	void	void	void	void	short
void	void	void	void	void	void	void	short
short	void	void	void	void	void	void	void
short	void	void	void	void	void	void	void
void	short	void	void	void	void	void	void
void	short	void	void	void	void	void	void
void	void	short	void	void	void	void	void
void	void	short	void	void	void	void	void
void	void	void	short	void	void	void	void
void	void	void	short	void	void	void	void
void	void	void	void	void	void	void	void
void	void	void	void	void	void	void	short
void	void	void	void	void	void	void	short
short	void	void	void	void	void	void	void
short	void	void	void	void	void	void	void
void	void	void	void	void	void	void	short
void	void	void	void	void	void	void	short
short	void	void	void	void	void	void	void
short	void	void	void	void	void	void	void
void	void	void	void	void	void	void	short
void	void	void	void	void	void	void	short
void	void	void	void	void	void	void	short
void	void	void	void	void	void	void	void
void	void	void	ramp	void	void	void	void
void	void	void	void	short	void	void	void
`,
};
