/* eslint-disable */
var levelData = {
  creatorName: "彡 𝐖𝕀єη𝔢ʳ∂𝓞ｇ彡",
  objectBlueprintGridText: `
  short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5
  short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5
  short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5
  lava	short	lava	lava	lava	lava	lava	lava
  lava	short	lava	lava	lava	lava	lava	lava
  lava	short	lava	lava	lava	lava	lava	lava
  lava	short	lava	lava	lava	short	lava	lava
  lava	lava	lava	lava	lava	short	lava	lava
  lava	lava	lava	lava	lava	short	lava	lava
  lava	lava	lava	lava	lava	short	lava	lava
  lava	lava	lava	lava	lava	short	lava	lava
  lava	lava	lava	lava	lava	short	lava	lava
  lava	lava	lava	short	short	short	lava	lava
  lava	lava	lava	short	short	lava	lava	lava
  lava	lava	lava	short	lava	lava	lava	lava
  lava	lava	lava	short	lava	lava	lava	lava
  lava	lava	lava	short	lava	lava	lava	lava
  lava	lava	lava	short	short	lava	lava	lava
  lava	lava	lava	short	short	short	lava	lava
  lava	lava	lava	lava	short	short	short	lava
  lava	lava	lava	lava	lava	short	short	short
  lava	lava	lava	lava	lava	lava	short	short
  lava	lava	lava	lava	lava	lava	lava	short
  lava	lava	lava	lava	lava	lava	short	short
  lava	lava	lava	lava	short	short	short	short
  lava	lava	lava	lava	short	short	short	lava
  lava	lava	lava	lava	short	short	lava	lava
  lava	lava	lava	short	short	lava	lava	lava
  lava	lava	short	short	short	lava	lava	lava
  lava	short	short	short	lava	lava	lava	lava
  lava	short	short	lava	lava	lava	lava	lava
  lava	short	lava	lava	lava	short	lava	lava
  lava	short	lava	lava	lava	short	lava	lava
  lava	lava	lava	lava	lava	short	lava	lava
  lava	lava	lava	lava	lava	short	lava	lava
  lava	lava	lava	lava	lava	short	short	lava
  lava	lava	lava	lava	lava	short	short	lava
  lava	lava	lava	lava	lava	short	short	lava
  lava	lava	lava	lava	lava	lava	short	lava
  lava	lava	lava	lava	lava	lava	short	lava
  lava	lava	lava	lava	lava	lava	short	lava
  lava	lava	short	lava	lava	lava	short	lava
  lava	lava	short	lava	lava	lava	lava	lava
  lava	lava	short	lava	lava	lava	lava	lava
  lava	lava	short	lava	lava	lava	lava	lava
  lava	lava	ramp@dt=2,da=3,dz=3,dr=2,ds=5	lava	lava	lava	lava	lava
  tall	tall	tall	tall	tall	tall	tall	tall
  tall	tall	tall	tall	tall	tall	tall	tall
  lava	lava	tall	tall	lava	tall	lava	tall
  tall	tall	tall	tall	lava	tall	tall	tall
  tall	tall	tall	tall	tall	tall	tall	tall
  tall	lava	lava	tall	tall	lava	lava	tall
  tall	tall	tall	tall	tall	lava	tall	tall
  tall	tall	tall	tall	tall	tall	tall	lava
  lava	tall	tall	lava	tall	tall	tall	lava
  tall	tall	tall	lava	tall	lava	tall	tall
  tall	lava	lava	tall	tall	tall	tall	tall
  tall	tall	lava	tall	tall	tall	tall	tall
  tall	tall	tall	tall	lava	lava	lava	tall
  tall	lava	tall	tall	tall	tall	tall	tall
  tall	lava	tall	tall	tall	tall	tall	lava
  tall	tall	tall	lava	tall	tall	tall	lava
  tall	tall	tall	tall	lava	lava	tall	tall
  tall	tall	tall	tall	tall	tall	tall	tall
  lava	lava	tall	tall	tall	tall	tall	tall
  tall	tall	tall	lava	lava	tall	tall	tall
  tall	tall	tall	tall	tall	tall	tall	tall
  short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5
  short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5
  short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5
  short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5
  lava	lava	short	lava	lava	short	lava	lava
  lava	lava	short	short	short	short	lava	lava
  lava	lava	short	short	short	short	lava	lava
  lava	lava	lava	short	short	lava	lava	lava
  lava	lava	short	short	short	short	lava	lava
  lava	lava	short	short	short	short	lava	lava
  lava	lava	short	lava	lava	short	lava	lava
  lava	lava	short	short	short	short	lava	lava
  lava	lava	lava	short	short	lava	lava	lava
  lava	lava	short	short	short	short	lava	lava
  lava	lava	short	short	short	short	lava	lava
  lava	short	short	lava	lava	short	short	lava
  lava	short	lava	lava	lava	lava	short	lava
  lava	short	short	lava	lava	short	short	lava
  lava	short	short	lava	lava	short	short	lava
  lava	lava	short	lava	lava	short	lava	lava
  lava	lava	short	lava	lava	short	lava	lava
  lava	lava	ramp@dt=2,da=3,dz=3,dr=2,ds=5	lava	lava	ramp@dt=2,da=3,dz=3,dr=2,ds=5	lava	lava
  lava	lava	tall	lava	lava	tall	lava	lava
  lava	lava	tall	lava	lava	tall	lava	lava
  lava	lava	tall	lava	lava	tall	lava	lava
  lava	lava	tall	tall	tall	tall	lava	lava
  lava	lava	tall	tall	tall	tall	lava	lava
  lava	lava	lava	tall	tall	lava	lava	lava
  tall@dt=2,da=3,dz=3,dr=2,ds=5	lava	lava	tall	tall	lava	lava	tall@dt=2,da=3,dz=3,dr=2,ds=5
  tall@dt=2,da=3,dz=3,dr=2,ds=5	lava	lava	lava	lava	lava	lava	tall@dt=2,da=3,dz=3,dr=2,ds=5
  tall@dt=2,da=3,dz=3,dr=2,ds=5	lava	lava	lava	lava	lava	lava	tall@dt=2,da=3,dz=3,dr=2,ds=5
  tall@dt=2,da=3,dz=3,dr=2,ds=5	lava	lava	lava	lava	lava	lava	tall@dt=2,da=3,dz=3,dr=2,ds=5
  tall@dt=2,da=3,dz=3,dr=2,ds=5	lava	lava	lava	lava	lava	lava	tall@dt=2,da=3,dz=3,dr=2,ds=5
`,
};
