/* eslint-disable */
var levelData = {
  creatorName: "彡 𝐖𝕀єη𝔢ʳ∂𝓞ｇ彡",
  objectBlueprintGridText: `
  ramp	lava	lava	lava	water	water	water	water
  tall	lava	lava	lava	water	water	water	water
  tall	tall	lava	lava	water	water	water	water
  lava	tall	tall	tall	short	water	water	water
  lava	lava	tall	tall	short	water	water	water
  lava	lava	lava	tall	short	water	water	water
  lava	lava	lava	tall	short	water	water	water
  lava	lava	tall	tall	short	short	water	water
  lava	lava	tall	lava	water	short	water	water
  tall	tall	tall	lava	water	short	short	short
  tall	lava	lava	lava	water	water	water	short
  tall	lava	lava	lava	water	water	water	short
  tall	tall	lava	lava	water	water	short	short
  lava	tall	tall	lava	water	short	short	water
  lava	lava	tall	lava	water	short	water	water
  lava	tall	tall	lava	water	short	short	water
  lava	tall	lava	lava	water	water	short	water
  lava	tall	tall	tall	short	short	short	water
  lava	lava	lava	tall	short	water	water	water
  lava	lava	tall	tall	short	short	water	water
  lava	lava	tall	lava	water	short	water	water
  lava	lava	tall	tall	short	short	water	water
  lava	lava	lava	tall	short	water	water	water
  lava	lava	short	tall	short	short	water	water
  lava	lava	short	lava	water	short	water	water
  void	short	short	void	void	ramp	void	void
  water	short	water	water	lava	tall	lava	lava
  water	short	water	water	lava	tall	lava	lava
  water	short	short	water	lava	tall	tall	lava
  water	water	short	water	lava	lava	tall	lava
  water	water	short	short	lava	lava	tall	tall
  water	water	water	short	lava	lava	lava	tall
  water	water	water	short	lava	lava	lava	tall
  water	water	void	short	lava	lava	void	tall
  water	water	void	ramp	lava	lava	void	ramp
  water	water	void	ramp	lava	lava	void	ramp
  water	water	ramp	void	lava	lava	ramp	void
  water	water	void	ramp	lava	lava	void	ramp
  water	water	ramp	void	lava	lava	ramp	void
  water	water	void	ramp	lava	lava	void	ramp
  water	water	ramp	void	lava	lava	ramp	void
  water	water	void	ramp	lava	lava	void	ramp
  water	water	ramp	void	lava	lava	ramp	void
  water	water	void	ramp	lava	lava	void	ramp
  water	water	ramp	void	lava	lava	ramp	void
  water	water	ramp	void	lava	lava	ramp	void
  water	water	void	ramp	lava	lava	void	ramp
  water	void	ramp	void	lava	void	ramp	void
  water	ramp	void	void	lava	ramp	void	void
  water	void	ramp	void	lava	void	ramp	void
  water	void	void	ramp	lava	void	void	ramp
  water	void	ramp	void	lava	void	ramp	void
  water	ramp	void	void	lava	ramp	void	void
  water	short	water	water	lava	tall	lava	lava
  water	short	water	water	lava	tall	lava	lava
  water	short	water	water	lava	tall	lava	lava
  water	short	water	water	lava	tall	lava	lava
  water	short	water	water	lava	tall	lava	lava
  void	short	void	void	void	water	void	void
  void	short	void	void	void	tall	void	void
  void	short	void	void	void	tall	void	void
  void	water	void	void	void	tall	void	void
  short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1
  ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1
  tall@da=-4,dt=1	tall@da=-4,dt=1	tall@da=-4,dt=1	tall@da=-4,dt=1	tall@da=-4,dt=1	tall@da=-4,dt=1	tall@da=-4,dt=1	tall@da=-4,dt=1
  short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1
  ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1
  tall@da=-4,dt=1	tall@da=-4,dt=1	tall@da=-4,dt=1	tall@da=-4,dt=1	tall@da=-4,dt=1	tall@da=-4,dt=1	tall@da=-4,dt=1	tall@da=-4,dt=1
  short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1
  short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1
  short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1
  short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1
  water	water	water	water	water	water	water	water
  ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1
  tall@da=-4,dt=1	tall@da=-4,dt=1	tall@da=-4,dt=1	tall@da=-4,dt=1	tall@da=-4,dt=1	tall@da=-4,dt=1	tall@da=-4,dt=1	tall@da=-4,dt=1
  tall@da=-4,dt=1	tall@da=-4,dt=1	tall@da=-4,dt=1	tall@da=-4,dt=1	tall@da=-4,dt=1	tall@da=-4,dt=1	tall@da=-4,dt=1	tall@da=-4,dt=1
  water	water	water	water	water	water	water	water
  short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1
  `
};