/* eslint-disable */
var levelData = {
    creatorName: 'Jon',
    objectBlueprintGridText: `
    short	void	void	void	void	void	void	void
    short	void	void	void	void	void	void	void
    short	void	void	void	void	void	void	void
    short	void	void	void	void	void	void	void
    short	void	void	void	tall	void	void	void
    short	void	void	void	tall	void	void	void
    void	void	void	void	tall	void	void	void
    void	void	void	void	tall	void	void	void
    void	void	void	void	short	void	void	void
    void	void	void	void	short	short	void	void
    void	void	void	void	void	short	void	void
    void	void	void	void	void	ramp	void	void
    void	void	void	void	tall	tall	short	void
    short	void	void	void	tall	void	short	void
    short	void	void	void	void	void	void	void
    short	void	void	void	void	void	void	void
    short	short	void	void	void	void	void	void
    water	short	void	void	void	void	void	void
    void	short	void	void	void	void	void	void
    void	ramp	void	void	void	void	void	void
    void	tall	void	void	void	void	void	void
    void	tall	void	void	void	void	void	void
    void	tall	tall	void	void	void	void	void
    void	void	tall	tall	void	void	void	void
    void	void	void	tall	tall	void	void	void
    void	void	void	void	tall	short	void	void
    void	void	void	void	void	short	short	void
    void	void	void	void	void	void	short	short
    short	void	void	void	void	void	void	short
    short	short	void	void	void	void	void	void
    void	short	short	void	void	void	void	void
    void	void	short	void	void	void	void	void
    void	short	short	void	void	void	void	void
    short	short	void	void	void	void	void	void
    short	void	void	void	void	void	void	short
    void	void	void	void	void	void	short	short
    void	void	void	void	void	void	short	void
    void	void	void	void	void	void	ramp	void
    void	void	void	void	void	void	short@dt=2,dz=2	void
    void	void	void	void	void	void	ramp	void
    void	void	void	void	void	void	short@dt=2,dz=2	void
    void	void	void	void	void	void	ramp	void
    void	void	void	void	void	void	short@dt=2,dz=2	void
    void	void	void	void	void	void	ramp	void
    void	void	void	void	void	void	short	void
    void	void	void	void	void	short@dt=2,dz=2	short	void
    void	void	void	void	short@dt=2,dz=2	short@dt=2,dz=2	void	void
    void	void	void	short@dt=2,dz=2	short@dt=2,dz=2	void	void	void
    void	void	short@dt=2,dz=2	short@dt=2,dz=2	void	void	void	void
    void	short@dt=2,dz=2	short@dt=2,dz=2	void	void	void	void	void
    short@dt=2,dz=2	short@dt=2,dz=2	void	void	void	void	void	void
    short@dt=2,dz=2	void	void	void	void	void	void	void
    short@dt=2,dz=2	short@dt=2,da=1	void	void	void	void	void	void
    void	short@dt=2,da=1	short@dt=2,da=1	void	void	void	void	void
    void	void	short@dt=2,da=1	short@dt=2,da=1	void	void	void	void
    void	void	void	short@dt=2,da=1	short@dt=2,da=1	void	void	void
    void	void	void	void	short@dt=2,da=1	short@dt=2,da=1	void	void
    void	void	void	void	void	short@dt=2,da=1	short@dt=2,da=1	void
    void	void	void	void	void	void	short@dt=2,da=1	short@dt=2,da=1
    void	void	void	void	void	void	void	short@dt=2,da=1
    void	void	void	void	void	void	void	ramp
    void	void	void	void	void	void	void	short@dt=2,dz=-2
    void	void	void	void	void	void	void	ramp
    void	void	void	void	void	void	void	short@dt=2,dz=-2
    void	void	void	void	void	void	void	ramp
    void	void	void	void	void	void	void	short@dt=2,dz=-2
    void	void	void	void	void	void	void	ramp
    void	void	void	void	void	void	void	short@dt=2,dz=-2
    void	void	void	void	void	void	void	short@dt=2,dz=2,da=1
    void	void	void	void	void	void	short@dt=2,dz=2,da=1	short@dt=2,dz=2,da=1
    void	void	void	void	void	short@dt=2,dz=2,da=1	short@dt=2,dz=2,da=1	void
    void	void	void	void	short@dt=2,dz=2,da=1	short@dt=2,dz=2,da=1	void	void
    void	void	void	short@dt=2,dz=2,da=1	short@dt=2,dz=2,da=1	void	void	void
    void	void	short@dt=2,dz=2,da=1	short@dt=2,dz=2,da=1	void	void	void	void
    void	short@dt=2,dz=2,da=1	short@dt=2,dz=2,da=1	void	void	void	void	void
    short@dt=2,dz=2,da=1	short@dt=2,dz=2,da=1	void	void	void	void	void	void
    short@dt=2,dz=2,da=1	void	void	void	void	void	void	short@dt=2,dz=2,da=1
    void	void	void	void	void	void	short@dt=2,dz=2,da=1	short@dt=2,dz=2,da=1
    void	void	void	void	void	short@dt=2,dz=2,da=1	short@dt=2,dz=2,da=1	void
    void	void	void	void	short@dt=2,dz=2,da=1	short@dt=2,dz=2,da=1	void	void
    void	void	void	short@dt=2,dz=2,da=1	short@dt=2,dz=2,da=1	void	void	void
    void	void	short@dt=2,dz=2,da=1	short@dt=2,dz=2,da=1	void	void	short@dt=2,dz=2,da=1	void
    void	void	short@dt=2,dz=2,da=1	void	void	void	short@dt=2,dz=2,da=1	void
    void	void	void	void	void	void	short@dt=2,dz=2,da=1	void
    void	void	void	void	void	void	short@dt=2,dz=2,da=1	void
    void	void	void	void	void	void	short@dt=2,dz=2,da=1	void
    void	void	void	void	void	short@dt=2,dz=2,da=1	short@dt=2,dz=2,da=1	void
    void	void	void	void	short@dt=2,dz=2,da=1	short@dt=2,dz=2,da=1	void	void
    void	void	void	short@dt=2,dz=2,da=1	short@dt=2,dz=2,da=1	void	void	void
    void	void	void	short@dt=2,dz=2,da=1	void	void	void	void
`
}