/* eslint-disable */
var levelData = {
  creatorName: "彡 𝐖𝕀єη𝔢ʳ∂𝓞ｇ彡",
  objectBlueprintGridText: `
short	void	void	void	void	void	void	void
short	void	void	void	void	void	void	void
short	short	void	void	void	void	void	void
void	short	void	void	void	void	void	void
void	short	short	void	void	void	void	void
void	void	short	void	void	void	void	void
void	void	short	short	void	void	void	void
void	void	void	short	void	void	void	void
void	void	void	short	short	void	void	void
void	void	void	void	short	void	void	void
void	void	void	void	short	void	void	void
void	void	void	short	short	void	void	void
void	void	void	short	void	void	void	void
void	void	void	short	short	void	void	void
void	void	void	void	short	void	void	void
void	void	void	short	short	void	void	void
void	void	void	short	void	void	void	void
void	void	short	short	void	void	void	void
void	void	short	void	void	void	void	void
void	short	short	void	void	void	void	void
void	short	void	void	void	void	void	void
void	short	void	void	void	void	void	void
void	void	void	void	void	short	short	void
void	void	void	void	void	short	short	void
void	void	void	void	void	short	short	void
void	void	short	void	void	void	void	void
void	void	short	void	void	void	void	void
void	void	short	void	void	void	void	void
short	short	short	short	short	short	short	short
lava	lava	short	lava	lava	lava	lava	lava
short	short	short	short	short	short	short	short
short	short	short	short	short	short	short	short
short	short	short	short	short	short	short	short
lava	lava	lava	lava	short	lava	lava	lava
short	short	short	short	short	short	short	short
short	short	short	short	short	short	short	short
short	short	short	short	short	short	short	short
lava	short	lava	lava	lava	lava	lava	lava
short	short	short	short	short	short	short	short
short	short	short	short	short	short	short	short
short	short	short	short	short	short	short	short
lava	lava	lava	short	lava	lava	lava	lava
short	short	short	short	short	short	short	short
short	short	short	short	short	short	short	short
short	short	short	short	short	short	short	short
short	short	short	short	short	short	short	short
short	lava	lava	lava	lava	lava	lava	lava
short	short	short	short	short	short	short	short
short	short	short	short	short	short	short	short
tall	tall	tall	tall	tall	tall	tall	tall
tall	tall	tall	tall	tall	tall	tall	tall
tall	tall	tall	tall	tall	tall	tall	tall
tall	tall	tall	tall	tall	tall	tall	tall
tall	tall	tall	tall	tall	tall	tall	tall
tall	tall	tall	tall	tall	tall	tall	tall
void	void	tall	tall	tall	void	void	void
void	void	tall	tall	tall	void	void	void
void	void	void	tall	tall	void	void	void
void	void	void	void	tall	tall	void	void
void	void	void	void	void	tall	tall	void
void	void	void	void	void	void	tall	tall
void	void	void	void	void	void	void	tall
void	void	void	void	void	void	tall	tall
void	void	void	void	void	tall	tall	void
void	void	void	void	tall	tall	void	void
void	void	tall	tall	tall	void	void	void
tall	tall	tall	tall	void	void	void	void
tall	tall	void	void	void	void	void	void
tall	tall	void	void	void	void	void	void
tall	tall	void	void	void	void	void	void
tall	tall	void	void	void	void	void	void
tall	tall	void	void	void	void	void	void
short	short	short	short	short	short	short	short
short	short	short	short	short	short	short	short
short	short	short	short	short	short	short	short
short	short	short	short	short	short	short	short
short	short	short	short	short	short	short	short
water	water	water	water	short@dt=2,dz=1	water	water	water
water	water	water	short@dt=2,dz=1	short@dt=2,dz=1	short@dt=2,dz=1	water	water
water	water	short@dt=2,dz=1	short@da=-4,dt=1	water	short@dt=2,dz=1	short@dt=2,dz=1	water
water	short@dt=2,dz=1	short@da=-4,dt=1	water	water	water	short@dt=2,dz=1	short@dt=2,dz=1
water	short@dt=2,dz=1	water	water	water	water	water	short@dt=2,dz=1
water	short@dt=2,dz=1	short@dt=2,dz=1	water	water	water	short@dt=2,dz=1	short@dt=2,dz=1
water	water	short@dt=2,dz=1	short@dt=2,dz=1	water	short@dt=2,dz=1	short@dt=2,dz=1	water
water	water	water	short@dt=2,dz=1	water	short@dt=2,dz=1	water	water
water	water	water	short@dt=2,dz=1	water	short@dt=2,dz=1	water	water
water	water	water	short@dt=2,dz=1	short@dt=2,dz=1	short@dt=2,dz=1	water	water
water	water	water	water	short@dt=2,dz=1	water	water	water
water	water	water	water	short@dt=2,dz=1	water	water	water
water	water	water	short@dt=2,dz=1	short@dt=2,dz=1	short@dt=2,dz=1	water	water
water	water	water	short@dt=2,dz=1	water	short@dt=2,dz=1	water	water
water	water	short@dt=2,dz=1	short@dt=2,dz=1	water	short@dt=2,dz=1	short@dt=2,dz=1	water
water	water	short@dt=2,dz=1	water	water	water	short@dt=2,dz=1	water
water	short@dt=2,dz=1	short@dt=2,dz=1	water	water	water	short@dt=2,dz=1	short@dt=2,dz=1
water	short@dt=2,dz=1	water	water	water	water	water	short@dt=2,dz=1
water	short@dt=2,dz=1	water	water	water	water	water	short@dt=2,dz=1
tall@da=-4,dt=1	tall@da=-4,dt=1	tall@da=-4,dt=1	tall@da=-4,dt=1	tall@da=-4,dt=1	tall@da=-4,dt=1	tall@da=-4,dt=1	tall@da=-4,dt=1
tall@da=-4,dt=1	tall@da=-4,dt=1	tall@da=-4,dt=1	tall@da=-4,dt=1	tall@da=-4,dt=1	tall@da=-4,dt=1	tall@da=-4,dt=1	tall@da=-4,dt=1
tall@da=-4,dt=1	tall@da=-4,dt=1	tall@da=-4,dt=1	tall@da=-4,dt=1	tall@da=-4,dt=1	tall@da=-4,dt=1	tall@da=-4,dt=1	tall@da=-4,dt=1
tall@da=-4,dt=1	tall@da=-4,dt=1	tall@da=-4,dt=1	tall@da=-4,dt=1	tall@da=-4,dt=1	tall@da=-4,dt=1	tall@da=-4,dt=1	tall@da=-4,dt=1
`,
};
