/* eslint-disable */
var levelData = {
    creatorName: 'BLX',
    objectBlueprintGridText: `
    ramp	water	water	water	water	water	water	water
    tall	water	water	water	water	water	water	water
    lava	water	short	water	lava	water	water	lava
    water	water	short	water	lava	water	water	water
    water	lava	lava	lava	water	water	water	water
    water	water	water	water	water	water	water	short
    water	water	water	water	water	water	water	short
    lava	water	water	water	water	water	lava	lava
    water	water	water	water	short	water	water	water
    water	water	water	water	ramp	water	water	water
    lava	water	water	water	lava	lava	water	water
    lava	water	short	water	water	water	water	water
    water	water	ramp	water	water	water	water	water
    water	lava	lava	lava	water	water	water	water
    water	water	water	water	water	water	water	short
    water	water	water	water	water	water	water	short
    water	water	water	water	water	water	water	ramp
    water	water	water	lava	water	water	lava	lava
    water	short	water	lava	water	water	water	water
    water	short	water	water	water	water	water	water
    lava	lava	lava	water	water	water	water	water
    water	water	water	water	short	water	water	water
    water	water	water	water	ramp	water	water	water
    lava	water	water	tall	lava	lava	water	water
    lava	water	tall	water	water	water	water	water
    water	tall	water	water	water	water	water	water
    tall	water	water	water	water	water	water	water
    water	water	water	water	water	water	water	tall
    water	water	water	water	water	water	tall	water
    water	water	water	water	water	tall	water	water
    water	water	water	water	tall	water	water	water
    lava	water	water	water	lava	lava	water	water
    lava	water	short	water	water	water	water	water
    water	water	ramp	water	water	water	water	water
    water	lava	lava	lava	water	water	water	water
    water	water	water	water	short	water	water	water
    water	water	water	water	short	water	water	water
    water	water	water	water	short	water	water	water
    water	water	water	water	ramp	water	water	water
    water	water	water	lava	lava	lava	water	water
    water	water	short	water	water	water	water	water
    water	water	short	water	water	water	water	water
    water	water	short	water	water	water	water	water
    water	lava	lava	lava	water	water	water	water
    water	water	water	water	water	water	short	water
    water	water	water	water	water	lava	lava	lava
    water	water	short	water	water	water	water	water
    water	lava	lava	lava	water	water	water	water
    water	water	water	water	water	water	short	water
    water	water	water	water	water	lava	lava	lava
    water	short	water	water	water	water	water	water
    water	water	short	water	water	water	water	water
    water	lava	lava	lava	water	water	water	water
    water	water	water	water	water	short	water	water
    water	water	water	water	lava	lava	lava	water
    water	water	short	water	water	water	water	water
    water	water	water	short	water	water	water	water
    water	water	water	water	short	water	water	water
    water	water	water	short	water	water	water	water
    water	water	water	water	ramp	water	water	water
    lava	water	water	lava	lava	water	water	water
    lava	water	water	water	water	water	short	water
    water	water	water	water	water	water	water	short
    water	water	water	water	water	water	ramp	water
    water	water	lava	water	water	water	lava	lava
    water	water	lava	water	ramp	water	water	water
    water	water	water	lava	lava	lava	water	water
    short	water	water	water	water	water	water	water
    lava	lava	water	water	water	water	water	lava
    water	water	water	water	water	short	water	water
    water	lava	water	water	ramp	lava	lava	water
    water	lava	water	water	water	water	lava	water
    water	water	water	water	water	water	ramp	water
    water	water	lava	water	water	lava	lava	water
    ramp	water	lava	water	water	water	water	water
    lava	water	water	water	lava	water	water	lava
    water	water	ramp	water	lava	water	water	water
    water	lava	lava	water	water	water	lava	water
    water	water	water	water	ramp	water	lava	water
    lava	water	water	water	lava	lava	water	water
    lava	water	ramp	water	water	water	water	water
    water	lava	lava	lava	water	water	water	water
    water	water	water	water	ramp	water	water	water
    lava	water	water	lava	lava	water	water	water
    lava	water	water	water	water	water	ramp	water
    water	water	water	water	water	lava	lava	lava
    water	water	water	water	ramp	water	water	water
    void	void	void	void	void	void	void	void
    void	void	void	void	void	void	void	ramp
    void	void	void	void	void	void	void	void
    void	void	void	ramp	void	void	void	void
    void	void	void	void	void	void	void	void
    water	water	water	water	water	water	water	ramp
    lava	water	water	lava	water	water	water	lava
    water	water	water	lava	water	ramp	water	water
    water	water	water	water	lava	lava	lava	water
    water	water	water	ramp	water	water	water	water
    water	water	water	lava	lava	water	water	lava
    water	short	water	water	water	water	water	lava
    void	void	void	void	void	void	void	void
`
}
