/* eslint-disable */
var levelData = {
    creatorName: 'BLX',
    objectBlueprintGridText: `
    ramp	water	water	water	water	water	water	water
    tall	water	water	water	water	water	water	water
    water	tall	water	water	water	water	water	water
    water	water	tall	water	water	water	water	water
    water	water	water	tall	water	water	water	water
    water	water	water	water	tall	water	water	water
    water	water	water	water	water	tall	water	water
    water	water	water	water	water	water	tall	water
    water	water	water	water	water	water	water	tall
    tall	water	water	water	water	water	water	water
    tall	water	water	water	water	water	water	water
    water	tall	water	water	water	water	water	water
    water	tall	water	water	water	water	water	water
    water	water	tall	water	water	water	water	water
    water	water	tall	water	water	water	water	water
    water	water	water	tall	water	water	water	water
    water	water	water	tall	water	water	water	water
    water	water	water	water	tall	water	water	water
    water	water	water	water	tall	water	water	water
    water	water	water	water	water	tall	water	water
    water	water	water	water	water	tall	water	water
    water	water	water	water	water	water	tall	water
    water	water	water	water	water	water	tall	water
    water	water	water	water	water	water	water	tall
    water	water	water	water	water	water	water	tall
    tall	water	water	water	water	water	water	water
    tall	water	water	water	water	water	water	water
    tall	water	water	water	water	water	water	water
    water	tall	water	water	water	water	water	water
    water	tall	water	water	water	water	water	water
    water	tall	water	water	water	water	water	water
    water	water	tall	water	water	water	water	water
    water	water	tall	water	water	water	water	water
    water	water	tall	water	water	water	water	water
    water	water	water	tall	water	water	water	water
    water	water	water	tall	water	water	water	water
    water	water	water	tall	water	water	water	water
    water	water	water	water	tall	water	water	water
    water	water	water	water	tall	water	water	water
    water	water	water	water	tall	water	water	water
    water	water	water	water	water	tall	water	water
    water	water	water	water	water	tall	water	water
    water	water	water	water	water	tall	water	water
    water	water	water	water	water	water	tall	water
    water	water	water	water	water	water	tall	water
    water	water	water	water	water	water	tall	water
    water	water	water	water	water	water	water	tall
    water	water	water	water	water	water	water	tall
    water	water	water	water	water	water	water	tall
    water	water	water	tall	water	water	water	water
    water	water	water	tall	water	water	water	water
    water	water	water	tall	water	water	water	water
    water	water	tall	water	water	water	water	water
    water	water	tall	water	water	water	water	water
    water	water	tall	water	water	water	water	water
    water	tall	water	water	water	water	water	water
    water	tall	water	water	water	water	water	water
    water	tall	water	water	water	water	water	water
    tall	water	water	water	water	water	water	water
    tall	water	water	water	water	water	water	water
    tall	water	water	water	water	water	water	water
    water	water	water	water	water	water	water	tall
    water	water	water	water	water	water	water	tall
    water	water	water	water	water	water	water	tall
    water	water	water	water	water	water	tall	water
    water	water	water	water	water	water	tall	water
    water	water	water	water	water	water	tall	water
    water	water	water	water	water	tall	water	water
    water	water	water	water	water	tall	water	water
    water	water	water	water	water	tall	water	water
    water	water	water	water	tall	water	water	water
    water	water	water	water	tall	water	water	water
    water	water	water	water	tall	water	water	water
    water	water	water	tall	water	water	water	water
    water	water	water	tall	water	water	water	water
    water	water	tall	water	water	water	water	water
    water	water	tall	water	water	water	water	water
    water	tall	water	water	water	water	water	water
    water	tall	water	water	water	water	water	water
    tall	water	water	water	water	water	water	water
    tall	water	water	water	water	water	water	water
    water	water	water	water	water	water	water	tall
    water	water	water	water	water	water	water	tall
    water	water	water	water	water	water	tall	water
    water	water	water	water	water	water	tall	water
    water	water	water	water	water	tall	water	water
    water	water	water	water	water	tall	water	water
    water	water	water	water	tall	water	water	water
    water	water	water	water	tall	water	water	water
    water	water	water	tall	water	water	water	water
    water	water	tall	water	water	water	water	water
    water	tall	water	water	water	water	water	water
    tall	water	water	water	water	water	water	water
    water	water	water	water	water	water	water	tall
    water	water	water	water	water	water	tall	water
    water	water	water	water	water	tall	water	water
    water	water	water	water	tall	water	water	water
    water	water	water	water	short	water	water	water
    water	water	water	water	short	water	water	water
    void	void	void	void	void	void	void	void
`
}