/* eslint-disable */
var levelData = {
  creatorName: "彡 𝐖𝕀єη𝔢ʳ∂𝓞ｇ彡",
  objectBlueprintGridText: `
  short@dt=2,da=3,dz=3,dr=2,ds=5	void	void	void	void	void	void	void
short@dt=2,da=3,dz=3,dr=2,ds=5	void	void	void	void	void	void	void
short@dt=2,da=3,dz=3,dr=2,ds=5	void	void	void	void	void	void	void
short@dt=2,da=3,dz=3,dr=2,ds=5	void	void	void	void	void	void	void
short@dt=2,da=3,dz=3,dr=2,ds=5	void	void	void	void	void	void	void
short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	void	void	void	void	void	void
void	short@dt=2,da=3,dz=3,dr=2,ds=5	void	void	void	void	void	void
short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	tall@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	tall@dt=2,da=3,dz=3,dr=2,ds=5
short@dt=2,da=3,dz=3,dr=2,ds=5	tall@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	tall@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5
short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	tall@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	tall@dt=2,da=3,dz=3,dr=2,ds=5
short@dt=2,da=3,dz=3,dr=2,ds=5	tall@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	tall@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5
short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	tall@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	tall@dt=2,da=3,dz=3,dr=2,ds=5
short@dt=2,da=3,dz=3,dr=2,ds=5	tall@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	tall@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5
short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	tall@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	tall@dt=2,da=3,dz=3,dr=2,ds=5
short@dt=2,dz=1	tall@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,dz=1	short@dt=2,da=3,dz=3,dr=2,ds=5	tall@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,dz=1	short@dt=2,dz=1
short@dt=2,dz=1	short@dt=2,dz=1	short@dt=2,dz=1	short@dt=2,dz=1	short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,dz=1	short@dt=2,dz=1	short@dt=2,dz=1
short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5	short@dt=2,da=3,dz=3,dr=2,ds=5
tall@dt=2,dz=2	tall@dt=2,dz=2	tall@dt=2,dz=2	tall@dt=2,dz=2	tall@dt=2,dz=2	tall@dt=2,dz=2	tall@dt=2,dz=2	tall@dt=2,dz=2
tall@dt=2,dz=2	tall@dt=2,dz=2	tall@dt=2,dz=2	tall@dt=2,dz=2	tall@dt=2,dz=2	tall@dt=2,dz=2	tall@dt=2,dz=2	tall@dt=2,dz=2
tall@dt=2,dz=2	tall@dt=2,dz=2	tall@dt=2,dz=2	tall@dt=2,dz=2	tall@dt=2,dz=2	tall@dt=2,dz=2	tall@dt=2,dz=2	tall@dt=2,dz=2
tall@dt=2,dz=2	tall@dt=2,dz=2	tall@dt=2,dz=2	tall@dt=2,dz=2	tall@dt=2,dz=2	tall@dt=2,dz=2	tall@dt=2,dz=2	tall@dt=2,dz=2
tall@dt=2,dz=2	tall@dt=2,dz=2	tall@dt=2,dz=2	tall@dt=2,dz=2	tall@dt=2,dz=2	tall@dt=2,dz=2	tall@dt=2,dz=2	tall@dt=2,dz=2
lava@dt=2,dz=2	lava@dt=2,dz=2	tall@dt=2,dz=2	lava@dt=2,dz=2	lava@dt=2,dz=2	tall@dt=2,dz=2	lava@dt=2,dz=2	lava@dt=2,dz=2
void	void	short@da=-4,dt=1	void	void	short@da=-4,dt=1	void	void
void	void	short@da=-4,dt=1	void	void	short@da=-4,dt=1	void	void
water	water	short@da=-4,dt=1	water	water	short@da=-4,dt=1	water	water
short	short	short	short	short	short	short	short
short	short	short	short	short	short	short	short
water	short	short	water	water	short	short	water
short	short	short	short	short	short	short	short
short	short	water	short	short	water	short	short
water	short	short	water	water	short	short	water
short	short	short	short	short	short	short	short
short	short	short	short	short	short	short	short
water	short	short	water	water	short	short	water
short	water	short	short	short	short	water	short
short	short	short	short	short	short	short	short
water	short	short	water	water	short	short	water
short	water	short	short	short	short	water	short
short	short	short	short	short	short	short	short
void	void	ramp	ramp	ramp	ramp	void	void
water	water	tall	tall	tall	tall	water	water
water	water	tall	tall	tall	tall	water	water
water	water	water	tall	tall	water	water	water
water	water	water	tall	tall	water	water	water
water	water	water	water	tall	water	water	water
water	water	water	tall	tall	water	water	water
water	water	water	tall	water	water	water	water
water	water	tall	tall	water	water	water	water
water	water	tall	water	water	water	water	water
water	tall	tall	water	water	water	water	water
water	tall	water	water	water	water	water	water
water	tall	water	water	water	tall	water	water
water	water	water	water	water	tall	water	water
water	water	water	water	water	tall	water	water
water	water	water	water	water	tall	water	water
water	water	water	water	water	ramp	water	water
short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1
short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1
short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1
short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1
short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1
short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1
water	water	water	water	water	water	water	water
short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1
short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1
short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1
ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1
short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1
short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1
short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1	short@da=-4,dt=1
void	short	void	void	void	void	void	void
void	short	void	void	void	void	void	void
void	short	void	void	void	void	void	void
void	short	void	void	void	void	void	void
void	void	void	void	void	short	void	void
void	void	void	void	void	short	void	void
void	void	void	void	void	short	void	void
void	short	void	void	void	void	void	void
void	short	void	void	void	void	void	void
void	short	void	void	void	void	void	void
void	short	void	void	void	void	void	void
void	void	void	void	void	short	void	void
void	void	void	void	void	short	void	void
void	void	void	void	void	short	void	void
short	short	short	short	short	short	short	short
short	short	short	short	short	short	short	short
short	short	short	short	short	short	short	short
lava	lava	lava	lava	lava	short	lava	lava
lava	lava	lava	lava	lava	short	lava	lava
short	short	short	short	short	short	short	short
short	short	short	short	short	short	short	short
lava	lava	lava	short	lava	lava	lava	lava
lava	lava	lava	short	lava	lava	lava	lava
short	short	short	short	short	short	short	short
short	short	short	short	short	short	short	short
short	short	short	short	short	short	short	short
short	short	short	short	short	short	short	short
lava	lava	lava	lava	lava	lava	lava	short
lava	lava	lava	lava	lava	lava	lava	short`,
};
