/* eslint-disable */
var levelData = {
  creatorName: "彡 𝐖𝕀єη𝔢ʳ∂𝓞ｇ彡",
  objectBlueprintGridText: `
  ramp	void	void	void	void	void	void	void
  ramp	void	void	void	void	void	void	void
  ramp	void	void	void	void	void	void	void
  void	ramp	void	void	void	void	void	void
  void	void	ramp	void	void	void	void	void
  void	void	void	ramp	void	void	void	void
  void	void	void	ramp	void	void	void	void
  void	void	void	ramp	void	void	void	void
  void	void	ramp	void	void	void	void	void
  void	void	void	ramp	void	void	void	void
  void	void	ramp	void	void	void	void	void
  void	void	void	ramp	void	void	void	void
  void	void	ramp	void	void	void	void	void
  void	void	void	ramp	void	void	void	void
  void	void	ramp	void	void	void	void	void
  void	void	void	ramp	void	void	void	void
  void	void	void	void	ramp	void	void	void
  void	void	void	void	ramp	void	void	void
  ramp	void	void	void	ramp	void	void	void
  ramp	void	void	void	void	void	void	void
  ramp	ramp	void	void	void	void	void	void
  void	ramp	void	void	void	void	void	void
  void	ramp	void	void	void	ramp	void	void
  void	void	void	void	void	ramp	void	void
  void	void	void	void	void	ramp	void	void
  void	void	void	void	void	ramp	ramp	void
  void	void	void	void	void	void	ramp	void
  void	void	ramp	void	void	void	ramp	void
  void	void	ramp	void	void	void	void	void
  void	void	ramp	void	void	void	void	void
  ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1
  ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1
  ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1
  ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1
  water	void	water	lava	ramp	lava	void	water
  void	water	void	lava	ramp	lava	water	void
  water	void	water	lava	ramp	lava	void	water
  ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1
  ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1
  ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1
  lava	water	void	water	void	water	lava	ramp
  lava	void	water	void	water	void	lava	ramp
  lava	water	void	water	void	water	lava	ramp
  ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1
  ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1
  ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1
  void	void	water	water	lava	ramp	lava	void
  water	void	water	void	lava	ramp	lava	water
  water	water	void	water	lava	ramp	lava	water
  ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1
  ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1
  ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1
  water	lava	ramp	lava	water	water	void	void
  void	lava	ramp	lava	void	water	water	water
  void	lava	ramp	lava	void	void	water	water
  ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1
  ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1
  ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1	ramp@da=-4,dt=1
  void	void	ramp	void	void	void	void	void
  void	void	ramp	ramp	void	void	void	void
  void	void	void	ramp	ramp	void	void	void
  void	void	void	void	ramp	ramp	void	void
  void	void	void	void	void	ramp	ramp	void
  void	void	void	void	void	void	ramp	ramp
  void	void	void	void	void	void	void	ramp
  ramp	void	void	void	void	void	void	void
  ramp	ramp	void	void	void	void	void	void
  void	ramp	ramp	void	void	void	void	void
  void	void	ramp	ramp	void	void	void	void
  void	void	void	ramp	ramp	void	void	void
  void	void	void	void	ramp	ramp	void	void
  void	void	void	void	void	ramp	ramp	void
  void	void	void	void	void	void	ramp	ramp
  void	void	void	void	void	void	void	ramp
  ramp	void	void	void	void	void	void	void
  ramp	ramp	void	void	void	void	void	void
  void	ramp	void	void	void	void	void	void
  void	ramp	ramp	ramp	void	void	void	void
  void	ramp	ramp	ramp	void	void	void	void
  void	ramp	ramp	ramp	void	void	void	void
  void	ramp	ramp	ramp	void	void	void	void
`,
};
