/* eslint-disable */
var levelData = {
  creatorName: "彡 𝐖𝕀єη𝔢ʳ∂𝓞ｇ彡",
  objectBlueprintGridText: `
  short	void	void	void	void	void	void	void
short	void	void	void	void	void	void	void
short	short	void	void	void	void	void	void
void	short	short	void	void	void	void	void
void	void	short	void	void	void	void	void
void	void	short	void	void	void	void	void
void	void	short	void	void	void	void	void
void	void	short	void	void	void	void	void
void	void	short	short	void	void	void	void
void	void	lava	short	void	void	void	void
void	void	short	short	void	void	void	void
void	void	short	lava	void	void	void	void
void	void	short	short	void	void	void	void
void	void	lava	short	void	void	void	void
void	void	short	short	void	void	void	void
void	void	short	void	void	void	void	void
void	void	short	void	void	void	void	void
tall	tall	tall	tall	tall	tall	tall	tall
short	short	short	short	short	short	short	short
short	short	short	short	short	short	short	short
short	short	short	short	short	short	short	short
short	short	short	short	short	short	short	short
short	short	short	short	short	short	short	short
short	short	short	short	short	short	short	short
void	void	ramp	ramp	void	void	void	void
void	void	tall	tall	void	void	void	void
void	void	tall	tall	void	void	void	void
void	void	tall	tall	void	void	void	void
void	void	void	tall	tall	void	void	void
void	void	void	void	tall	void	void	void
void	void	void	tall	tall	void	void	void
void	void	tall	tall	void	void	void	void
short	short	short	short	short	short	short	short
short	short	short	short	short	short	short	short
water	water	water	water	water	water	water	water
short	short	short	short	short	short	short	short
short	short	short	short	short	short	short	short
water	water	water	water	water	water	water	water
ramp	ramp	ramp	ramp	ramp	ramp	ramp	ramp
short	short	short	short	short	short	short	short
short	short	short	short	short	short	short	short
short	water	short	lava	short	water	short	lava
short	short	short	short	short	short	short	short
short	short	short	short	short	short	short	short
lava	short	water	short	lava	short	water	short
short	short	short	short	short	short	short	short
short	short	short	short	short	short	short	short
short	short	short	short	short	short	short	short
short	short	short	short	short	short	short	short
short	water	short	lava	short	water	short	lava
short	short	short	short	short	short	short	short
short	short	short	short	short	short	short	short
water	short	lava	short	water	short	lava	short
short	short	short	short	short	short	short	short
short	short	short	short	short	short	short	short
short	short	short	short	short	short	short	short
short	short	short	short	short	short	short	short
void	void	void	short	short	void	void	void
void	void	short	short	short	short	void	void
void	short	short	lava	lava	short	short	void
void	short	lava	lava	lava	lava	short	void
void	short	short	lava	lava	short	short	void
void	void	short	lava	lava	short	void	void
void	void	short	short	short	short	void	void
void	void	void	short	short	void	void	void
void	void	void	short	short	void	void	void
void	void	void	ramp	ramp	void	void	void
void	void	void	tall	tall	void	void	void
void	void	tall	tall	tall	tall	void	void
void	void	tall	lava	lava	tall	void	void
void	void	tall	tall	tall	tall	void	void
void	void	lava	tall	tall	lava	void	void
void	void	tall	tall	tall	tall	void	void
void	void	tall	lava	lava	tall	void	void
void	void	tall	lava	lava	tall	void	void
void	void	tall	lava	lava	tall	void	void
void	void	tall	tall	tall	tall	void	void
void	void	ramp	void	void	ramp	void	void
void	void	ramp	void	void	ramp	void	void
void	void	ramp	void	void	ramp	void	void
void	void	ramp	void	void	ramp	void	void
void	void	ramp	void	void	ramp	void	void
void	void	ramp	ramp	ramp	ramp	void	void
void	void	void	ramp	ramp	void	void	void
void	void	void	ramp	ramp	void	void	void
void	void	void	ramp	ramp	void	void	void
void	void	void	ramp	ramp	void	void	void
void	void	void	tall	tall	void	void	void
void	void	void	tall	tall	void	void	void
void	void	void	tall	tall	void	void	void
short	short	short	short	short	short	short	short
lava@dt=2,dz=1	lava@dt=2,dz=1	lava@dt=2,dz=1	short	lava@dt=2,dz=1	lava@dt=2,dz=1	lava@dt=2,dz=1	lava@dt=2,dz=1
lava@dt=2,dz=1	lava@dt=2,dz=1	lava@dt=2,dz=1	short	lava@dt=2,dz=1	lava@dt=2,dz=1	lava@dt=2,dz=1	lava@dt=2,dz=1
lava@dt=2,dz=1	lava@dt=2,dz=1	lava@dt=2,dz=1	short	lava@dt=2,dz=1	lava@dt=2,dz=1	lava@dt=2,dz=1	lava@dt=2,dz=1
lava@dt=2,dz=1	lava@dt=2,dz=1	lava@dt=2,dz=1	short	short	lava@dt=2,dz=1	lava@dt=2,dz=1	lava@dt=2,dz=1
lava@dt=2,dz=1	lava@dt=2,dz=1	lava@dt=2,dz=1	lava@dt=2,dz=1	short	lava@dt=2,dz=1	lava@dt=2,dz=1	lava@dt=2,dz=1
lava@dt=2,dz=1	lava@dt=2,dz=1	lava@dt=2,dz=1	lava@dt=2,dz=1	short	short	lava@dt=2,dz=1	lava@dt=2,dz=1
lava@dt=2,dz=1	lava@dt=2,dz=1	lava@dt=2,dz=1	lava@dt=2,dz=1	lava@dt=2,dz=1	short	lava@dt=2,dz=1	lava@dt=2,dz=1
lava@dt=2,dz=1	lava@dt=2,dz=1	lava@dt=2,dz=1	lava@dt=2,dz=1	lava@dt=2,dz=1	short	short	lava@dt=2,dz=1
tall@dt=2,dz=1	tall@dt=2,dz=1	tall@dt=2,dz=1	tall@dt=2,dz=1	tall@dt=2,dz=1	tall@dt=2,dz=1	tall@dt=2,dz=1	tall@dt=2,dz=1`,
};
