/* eslint-disable */
var levelData = {
  creatorName: "彡 𝐖𝕀єη𝔢ʳ∂𝓞ｇ彡",
  objectBlueprintGridText: `
  short	water	lava	lava	lava	lava	lava	water
  short	water	lava	lava	lava	lava	lava	water
  short	water	lava	lava	lava	lava	lava	water
  short	water	lava	lava	lava	lava	lava	water
  water	short	lava	lava	lava	lava	lava	lava
  short	water	lava	lava	lava	lava	lava	water
  short	water	lava	lava	lava	lava	lava	water
  short	water	lava	lava	lava	lava	lava	water
  short	water	lava	lava	lava	lava	lava	water
  water	short	water	lava	lava	lava	lava	lava
  lava	water	short	water	water	lava	lava	lava
  lava	lava	water	short	short	water	lava	lava
  lava	lava	lava	water	short	water	lava	lava
  lava	lava	lava	water	short	water	lava	lava
  lava	lava	water	short	water	lava	lava	lava
  lava	water	short	water	lava	lava	lava	lava
  water	short	water	lava	lava	water	lava	lava
  lava	water	lava	lava	lava	ramp	lava	lava
  water	water	water	water	water	tall	water	water
  water	water	water	water	lava	tall	lava	water
  water	water	water	water	lava	tall	lava	water
  water	water	water	water	lava	tall	lava	water
  water	tall	water	water	water	lava	water	water
  water	tall	water	water	water	water	water	water
  lava	tall	lava	water	water	water	water	water
  water	tall	lava	water	water	water	water	water
  tall	water	lava	water	water	water	water	water
  water	tall	lava	water	water	water	water	water
  lava	tall	lava	water	water	water	water	water
  lava	tall	lava	lava	water	water	water	water
  lava	lava	lava	lava	water	short	water	lava
  lava	lava	lava	lava	water	short	water	lava
  lava	lava	lava	lava	water	short	water	lava
  lava	lava	lava	water	ramp	water	lava	lava
  lava	lava	water	short	water	water	lava	lava
  lava	water	ramp	water	lava	lava	lava	lava
  water	short	water	lava	lava	lava	lava	lava
  ramp	water	lava	lava	lava	lava	lava	lava
  tall	void	void	void	void	void	void	void
  tall	void	void	void	void	void	void	void
  void	tall	void	void	void	void	void	void
  tall	void	void	void	void	void	void	void
  tall	tall	tall	void	void	void	void	void
  void	void	tall	void	void	void	void	void
  void	void	tall	void	void	void	void	void
  void	void	void	void	void	void	tall	void
  void	void	void	void	void	void	tall	void
  void	void	void	void	void	void	short	void
  void	void	void	void	void	void	short	void
  void	void	void	void	void	void	short	void
  water	water	water	water	water	void	short	void
  water	water	water	water	void	short	void	water
  water	water	water	water	short	void	water	water
  water	water	water	void	short	water	water	water
  water	water	void	short	void	water	water	water
  water	void	short	void	water	water	water	water
  water	void	short	void	water	water	water	water
  water	void	short	void	water	water	water	water
  water	water	void	short	void	water	water	water
  water	water	water	void	short	void	water	water
  water	water	water	void	short	void	water	water
  water	water	void	short	void	water	water	water
  water	water	void	short	void	water	water	water
  water	water	water	void	short	void	water	water
  water	water	water	water	short	water	water	water
  void	void	void	water	ramp	lava	void	void
  void	void	lava	ramp	water	void	void	void
  void	void	void	water	ramp	lava	void	void
  void	void	lava	ramp	water	void	void	void
  void	void	void	water	ramp	lava	void	void
  void	void	void	void	water	ramp	lava	void
  void	void	void	lava	ramp	water	void	void
  tall	tall	tall	tall	tall	tall	tall	tall
  tall	tall	tall	tall	tall	tall	tall	tall
  lava	lava	lava	lava	lava	lava	tall	lava
  tall	tall	tall	tall	tall	tall	tall	tall
  tall	tall	tall	tall	tall	tall	tall	tall
  lava	lava	tall	lava	lava	lava	lava	lava
  tall	tall	tall	tall	tall	tall	tall	tall
  tall	tall	tall	tall	tall	tall	tall	tall
  tall	tall	tall	tall	tall	tall	tall	tall
  lava	lava	lava	lava	lava	tall	lava	lava
  tall	tall	tall	tall	tall	tall	tall	tall
  tall	tall	tall	tall	tall	tall	tall	tall
  lava	lava	lava	tall	lava	lava	lava	lava
  void	void	tall	tall	tall	void	void	void
  void	void	tall	lava	tall	void	void	void
  void	void	tall	void	tall	void	void	void
  void	void	tall	void	tall	void	void	void
  void	void	void	tall	void	void	void	void
  void	void	tall	void	tall	void	void	void
  void	void	void	tall	void	void	void	void
  void	water	lava	short@dt=5,da=2,dz=4,dr=3,ds=5	water	lava	void	water
  void	water	void	short@dt=5,da=2,dz=4,dr=3,ds=5	water	lava	void	water
  void	water	short@dt=5,da=2,dz=4,dr=3,ds=5	void	water	lava	void	water
  void	short@dt=5,da=2,dz=4,dr=3,ds=5	void	void	water	lava	void	water
  void	short@dt=5,da=2,dz=4,dr=3,ds=5	lava	void	water	lava	void	water
  void	short@dt=5,da=2,dz=4,dr=3,ds=5	lava	void	water	lava	void	water
  void	short@dt=5,da=2,dz=4,dr=3,ds=5	lava	void	water	lava	void	water
  short@dt=5,da=2,dz=4,dr=3,ds=5	void	lava	void	water	lava	void	water
`,
};
